### ISSUE TITLE
Error getting HAR from FF

### ISSUE THREAD

**Issue by soulgalore** [sitespeedio/coach#32] opened 2016-02-28 14:08 UTC
http://sj.se
```
[2016-02-28 14:56:30] Error from Firefox HAR generation: {"message":"JSON.parse is not a function","stackTrace":[{"methodName":"anonymous/triggerExport/<","fileName":"http://www.sj.se/ line 69 > Function","lineNumber":7,"columnNumber":29}]}
Error running advice:  { message: 'JSON.parse is not a function',
  stackTrace: 
   [ { methodName: 'anonymous/triggerExport/<',
       fileName: 'http://www.sj.se/ line 69 > Function',
       lineNumber: 7,
       columnNumber: 29 } ] }
```

**Comment by tobli** [comment] 2016-05-24 20:58
I can't reproduce this when running (with Firefox 46):
```sh
webcoach http://www.sj.se
```

I guess the code, browser and site have all changed since February… Hopefully this error is no more, so closing.

**Closed by tobli** 2016-05-24 20:58 UTC
Labels: bug

**Comment by soulgalore** [comment] 2016-05-24 21:20
Yep it was the old version of the site. They used to override JSON, but we handle that nowadays (I think).

**Comment by tobli** [comment] 2016-05-24 21:21
Right, would be useful to have as a test case if we could find something similar and extract it.
